[window]
padding = {x = 8, y = 8}
opacity = 0.9 
blur = true

[font]
normal = { family = "JetBrains Mono Nerd Font" , style = "bold"}
size = 11

[selection]
save_to_clipboard = true

[colors.primary]
foreground = "#D8DEE9"
background = "#2E3440"

[colors.normal]
black = "#3B4252"
red = "#BF616A"
green = "#A3BE8C"
yellow = "#EBCB8B"
blue = "#81A1C1"
magenta = "#B48EAD"
cyan = "#88C0D0"
white = "#E5E9F0"

[colors.bright]
black = "#4C566A"
red = "#BF616A"
green = "#A3BE8C"
yellow = "#EBCB8B"
blue = "#81A1C1"
magenta = "#B48EAD"
cyan = "#8FBCBB"
white = "#ECEFF4"

